'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3512.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3512.0.
'
Namespace localhost
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="StockQuote_BusinessObjectSoap", [Namespace]:="http://www.prosetech.com/Stocks")>  _
    Public Class StockQuote_BusinessObject
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/ASP.NET/Chapter19/WebServices/StockQuote_BusinessObject.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prosetech.com/Stocks/GetStockQuote", RequestNamespace:="http://www.prosetech.com/Stocks", ResponseNamespace:="http://www.prosetech.com/Stocks", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStockQuote(ByVal Ticker As String) As StockInfo
            Dim results() As Object = Me.Invoke("GetStockQuote", New Object() {Ticker})
            Return CType(results(0),StockInfo)
        End Function
        
        '<remarks/>
        Public Function BeginGetStockQuote(ByVal Ticker As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetStockQuote", New Object() {Ticker}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetStockQuote(ByVal asyncResult As System.IAsyncResult) As StockInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),StockInfo)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.prosetech.com/Stocks")>  _
    Public Class StockInfo
        
        '<remarks/>
        Public Price As Decimal
        
        '<remarks/>
        Public Symbol As String
        
        '<remarks/>
        Public High_52Week As Decimal
        
        '<remarks/>
        Public Low_52Week As Decimal
        
        '<remarks/>
        Public CompanyName As String
    End Class
End Namespace
