'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.288
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
'
Namespace localhost3
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="StockQuote_SessionStateSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class StockQuote_SessionState
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/ASP.NET/Chapter20/WebServices/StockQuote_SessionState.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockQuote", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStockQuote(ByVal Ticker As String) As Decimal
            Dim results() As Object = Me.Invoke("GetStockQuote", New Object() {Ticker})
            Return CType(results(0),Decimal)
        End Function
        
        '<remarks/>
        Public Function BeginGetStockQuote(ByVal Ticker As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetStockQuote", New Object() {Ticker}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetStockQuote(ByVal asyncResult As System.IAsyncResult) As Decimal
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Decimal)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockUsage", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStockUsage(ByVal Ticker As String) As CounterInfo
            Dim results() As Object = Me.Invoke("GetStockUsage", New Object() {Ticker})
            Return CType(results(0),CounterInfo)
        End Function
        
        '<remarks/>
        Public Function BeginGetStockUsage(ByVal Ticker As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetStockUsage", New Object() {Ticker}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetStockUsage(ByVal asyncResult As System.IAsyncResult) As CounterInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),CounterInfo)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class CounterInfo
        
        '<remarks/>
        Public GlobalRequests As Integer
        
        '<remarks/>
        Public SessionRequests As Integer
    End Class
End Namespace
