'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.288
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
'
Namespace localhost4
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="StockQuote_SoapSecuritySoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class StockQuote_SoapSecurity
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Public SecurityHeaderValue As SecurityHeader
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/ASP.NET/Chapter20/WebServices/StockQuote_SoapSecurity.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockQuote", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStockQuote(ByVal Ticker As String) As Integer
            Dim results() As Object = Me.Invoke("GetStockQuote", New Object() {Ticker})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginGetStockQuote(ByVal Ticker As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetStockQuote", New Object() {Ticker}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetStockQuote(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/", IsNullable:=false)>  _
    Public Class SecurityHeader
        Inherits SoapHeader
        
        '<remarks/>
        Public UserID As String
        
        '<remarks/>
        Public Password As String
        
        '<remarks/>
        Public Key As String
    End Class
End Namespace
